version: '3'
services:
  # Angular Application
  angular-app:
    image: cmui:dev
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
    volumes:
      - ./app:/app
    command: ["npm", "start"]

  # Nginx Server
  nginx:
    image: nginx:latest
    ports:
      - "81:81"
    volumes:
      - ./app/dist:/usr/share/nginx/html
