# https://computingforgeeks.com/how-to-install-latest-redis-on-centos-7/
# it is required to run install_devtools.yml before this
---
- hosts: 192.168.1.121
  vars:
    remote_app_deploy_dir: /home/teamwork/nodeapps/cm
    remote_log_dir: "{{remote_app_deploy_dir}}/log"
    app_port: 3000
  become: false
  tasks:
  - name: Create app deploy directory ({{remote_app_deploy_dir}}) if it does not exist
    file:
      path: "{{remote_app_deploy_dir}}"
      state: directory

  - name: Stop CM application
    command: pm2 stop "cm-api"
    args:
      chdir: "{{remote_app_deploy_dir}}"

  - name: Delete CM application
    command: pm2 delete "cm-api"
    args:
      chdir: "{{remote_app_deploy_dir}}"

  - name: Delete app directory {{remote_app_deploy_dir}}
    file:
      path: "{{remote_app_deploy_dir}}"
      state: absent

  - name: Create app deploy directory ({{remote_app_deploy_dir}}) if it does not exist
    file:
      path: "{{remote_app_deploy_dir}}"
      state: directory

  - name: Create log directory ({{remote_log_dir}}) if it does not exist
    file:
      path: "{{remote_log_dir}}"
      state: directory

  - name: Copy cm.zip to remote and Extract into into {{remote_app_deploy_dir}}
    unarchive:
      src: ../dist/cm.zip
      dest: "{{remote_app_deploy_dir}}"

  - name: Change swagger host to machine ip
    replace:
      path: "{{remote_app_deploy_dir}}/config/swagger.js"
      regexp: "host: '127.0.0.1:3000'"
      replace: "host: '{{inventory_hostname}}:{{app_port}}'"

  - name: Change db url in .env
    replace:
      path: "{{remote_app_deploy_dir}}/.env"
      regexp: "DB_URL_CM=mariadb://devuser:devuser@123@192.168.1.132:3310/cm"
      replace: "DB_URL_CM=mariadb://appuser:appuser@123@192.168.1.136:3306/cm"

  - name: Change maria host in .env
    replace:
      path: "{{remote_app_deploy_dir}}/.env"
      regexp: "MARIA_DB_CM_HOST=192.168.1.132"
      replace: "MARIA_DB_CM_HOST=192.168.1.136"

  - name: Change maria port in .env
    replace:
      path: "{{remote_app_deploy_dir}}/.env"
      regexp: "MARIA_DB_CM_PORT=3310"
      replace: "MARIA_DB_CM_PORT=3306"

  - name: Change maria username in .env
    replace:
      path: "{{remote_app_deploy_dir}}/.env"
      regexp: "MARIA_DB_CM_USER=devuser"
      replace: "MARIA_DB_CM_USER=appuser"

  - name: Change maria password in .env
    replace:
      path: "{{remote_app_deploy_dir}}/.env"
      regexp: "MARIA_DB_CM_PASSWORD=devuser@123"
      replace: "MARIA_DB_CM_PASSWORD=appuser@123"

  - name: Change maria db in .env
    replace:
      path: "{{remote_app_deploy_dir}}/.env"
      regexp: "MARIA_DB_CM_DATABASE=cm"
      replace: "MARIA_DB_CM_DATABASE=cm"

  - name: Change maria pool limit (fastify) in .env
    replace:
      path: "{{remote_app_deploy_dir}}/.env"
      regexp: "MARIA_DB_CM_CONNECTION_LIMIT=20"
      replace: "MARIA_DB_CM_CONNECTION_LIMIT=25"

  - name: Change maria pool limit (other) in .env
    replace:
      path: "{{remote_app_deploy_dir}}/.env"
      regexp: "MARIA_DB_CM_CONNECTION_LIMIT_FOR_OTHERS=5"
      replace: "MARIA_DB_CM_CONNECTION_LIMIT_FOR_OTHERS=5"

  - name: Change redis ip for normal group
    replace:
      path: "{{remote_app_deploy_dir}}/.env"
      regexp: "REDIS_GROUP_HOST=192.168.1.168"
      replace: "REDIS_GROUP_HOST=192.168.1.150"

  - name: Change redis port for normal group
    replace:
      path: "{{remote_app_deploy_dir}}/.env"
      regexp: "REDIS_GROUP_PORT=6379"
      replace: "REDIS_GROUP_PORT=6379"

  - name: Change redis db for normal group
    replace:
      path: "{{remote_app_deploy_dir}}/.env"
      regexp: "REDIS_GROUP_DB=1"
      replace: "REDIS_GROUP_DB=1"

  - name: Change redis ip for exclude group
    replace:
      path: "{{remote_app_deploy_dir}}/.env"
      regexp: "REDIS_EGROUP_HOST=192.168.1.168"
      replace: "REDIS_EGROUP_HOST=192.168.1.214"

  - name: Change redis port for exclude group
    replace:
      path: "{{remote_app_deploy_dir}}/.env"
      regexp: "REDIS_EGROUP_PORT=6380"
      replace: "REDIS_EGROUP_PORT=6379"

  - name: Change redis db for exclude group
    replace:
      path: "{{remote_app_deploy_dir}}/.env"
      regexp: "REDIS_EGROUP_DB=0"
      replace: "REDIS_EGROUP_DB=1"

  - name: Change redis ip for wallet
    replace:
      path: "{{remote_app_deploy_dir}}/.env"
      regexp: "REDIS_WALLET_HOST=192.168.1.122"
      replace: "REDIS_WALLET_HOST=192.168.1.148"

  - name: Change redis port for wallet
    replace:
      path: "{{remote_app_deploy_dir}}/.env"
      regexp: "REDIS_WALLET_PORT=6379"
      replace: "REDIS_WALLET_PORT=6379"

  - name: Change redis db for wallet
    replace:
      path: "{{remote_app_deploy_dir}}/.env"
      regexp: "REDIS_WALLET_DB=13"
      replace: "REDIS_WALLET_DB=1"

  - name: Change url for password service
    replace:
      path: "{{remote_app_deploy_dir}}/.env"
      regexp: "PASSWORD_SERVICE_URL=http://192.168.1.128:9380/password/reset"
      replace: "PASSWORD_SERVICE_URL=http://192.168.1.245:9380/password/reset"

  - name: Change url for msg tool service
    replace:
      path: "{{remote_app_deploy_dir}}/.env"
      regexp: "MSGINFO_SERVICE_URL=http://192.168.1.128:8980/msgtool/msginfo"
      replace: "MSGINFO_SERVICE_URL=http://192.168.1.245:8980/msgtool/msginfo"

  - name: install node dependencies
    shell: yarn install
    args:
      chdir: "{{remote_app_deploy_dir}}"

  - name: Start CM application
    command: pm2 start app.js --name "cm-api"
    args:
      chdir: "{{remote_app_deploy_dir}}"
